model:
  feature_encoder_cfg:
    flow_encoder_cfg:
      model_name: "resnet50"
      pretrained: False
    lsd_encoder_cfg:
      unet_cfg: null
  num_encoder_layers: 2
  num_decoder_layers: 2
  embedding_meta:
    rel:
      cutoff_spatial: 256
      cutoff_temporal: 32
      n_spatial: 32
      n_temporal: 16

dataset:
  train_dataset:
    slp_files: ['190612_110405_wt_18159111_rig2.2@11730.slp']
    video_files: ['190612_110405_wt_18159111_rig2.2@11730.mp4']
    clip_length: 16
