name: biogtr

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch-cuda=12.1
  #- cudatoolkit=12.1
  - cudnn
  - pytorch
  - torchvision
  - lightning
  - imageio
  - av
  - ffmpeg
  - albumentations
  - pip
  - pip:
    - opencv-python-headless
    - matplotlib
    - sleap-io
    - "--editable=.[dev]"
    - imageio[ffmpeg]
    - hydra-core
    - motmetrics
    - seaborn
    - wandb