[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "biogtr"
authors = [
    {name = "Arlo Sheridan", email = "asheridan@salk.edu"},
    {name = "Aaditya Prasad", email = "aprasad@salk.edu"},
    {name = "Vincent Tu", email = "vtu@ucsd.edu"},
    {name = "Uri Manor", email = "umanor@salk.edu"},
    {name = "Talmo Pereira", email = "talmo@salk.edu"},
]
description = "Global Tracking Transformers for biological multi-object tracking."
requires-python = ">=3.8"
keywords = ["gtr", "mot"]
license = {text = "BSD-3-Clause"}
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
dependencies = [
    "torch >= 2.0.0",
    "torchvision",
    "lightning",
    "imageio",
    "imageio-ffmpeg",
    "av",
    "albumentations",
    "hydra-core",
    "sleap-io"
]
dynamic = ["version", "readme"]

[tool.setuptools.dynamic]
version = {attr = "biogtr.version.__version__"}
readme = {file = ["README.md"]}

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "black",
    "pydocstyle",
    "toml",
    "twine",
    "build"
]

[project.scripts]
biogtr = "biogtr.cli:cli"

[project.urls]
Homepage = "https://github.com/talmolab/biogtr"
Repository = "https://github.com/talmolab/biogtr"

[tool.black]
line-length = 88

[pydocstyle]
convention = "google"
match-dir = "sleap_roots"